name: Run unittest tests on Push
on: [push]

jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup environment variables
      run: |
        echo "DB_USER=root" >> $GITHUB_ENV
        echo "DB_NAME=test" >> $GITHUB_ENV
        echo "DB_PASSWORD=root" >> $GITHUB_ENV
        echo "DB_HOST=localhost" >> $GITHUB_ENV
        echo "TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV
        echo "BASE_PATH=${{ secrets.BASE_PATH }}" >> $GITHUB_ENV
        echo "STEAM_ID=${{ secrets.STEAM_ID }}" >> $GITHUB_ENV

    - name: Setup Database
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE test;' -uroot -proot

    - name: Run tests
      run: | 
        python -m unittest discover -s tests
      

